"""Added is_active column on both counsellor and auditor

Revision ID: 0271e52e936d
Revises: 49011c0d6b17
Create Date: 2025-07-22 11:39:16.767369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0271e52e936d"
down_revision: Union[str, Sequence[str], None] = "49011c0d6b17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auditors", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.drop_constraint(op.f("calls_auditor_id_fkey"), "calls", type_="foreignkey")
    op.create_foreign_key(
        None, "calls", "auditors", ["auditor_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("counsellors", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("counsellors", "is_active")
    op.drop_constraint(None, "calls", type_="foreignkey")
    op.create_foreign_key(
        op.f("calls_auditor_id_fkey"),
        "calls",
        "auditors",
        ["auditor_id"],
        ["id"],
    )
    op.drop_column("auditors", "is_active")
    # ### end Alembic commands ###
