"""Established cascade relationship between counsellor -> calls and leads

Revision ID: 49011c0d6b17
Revises: 9f55e197c2d6
Create Date: 2025-07-22 11:00:09.293009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49011c0d6b17"
down_revision: Union[str, Sequence[str], None] = "9f55e197c2d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("calls_counsellor_id_fkey"), "calls", type_="foreignkey")
    op.create_foreign_key(
        None,
        "calls",
        "counsellors",
        ["counsellor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("leads_counsellor_id_fkey"), "leads", type_="foreignkey")
    op.create_foreign_key(
        None,
        "leads",
        "counsellors",
        ["counsellor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "leads", type_="foreignkey")
    op.create_foreign_key(
        op.f("leads_counsellor_id_fkey"),
        "leads",
        "counsellors",
        ["counsellor_id"],
        ["id"],
    )
    op.drop_constraint(None, "calls", type_="foreignkey")
    op.create_foreign_key(
        op.f("calls_counsellor_id_fkey"),
        "calls",
        "counsellors",
        ["counsellor_id"],
        ["id"],
    )
    # ### end Alembic commands ###
