"""Established cascade relationship between counsellor and auditor

Revision ID: 9861fa198790
Revises: 3460bd6feaac
Create Date: 2025-07-21 23:59:16.208730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9861fa198790"
down_revision: Union[str, Sequence[str], None] = "3460bd6feaac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("counsellors_auditor_id_fkey"), "counsellors", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "counsellors",
        "auditors",
        ["auditor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "counsellors", type_="foreignkey")
    op.create_foreign_key(
        op.f("counsellors_auditor_id_fkey"),
        "counsellors",
        "auditors",
        ["auditor_id"],
        ["id"],
    )
    # ### end Alembic commands ###
