"""Established cascade relationship between counsellor and auditor - fixed

Revision ID: 9f55e197c2d6
Revises: 9861fa198790
Create Date: 2025-07-22 00:02:39.080307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f55e197c2d6"
down_revision: Union[str, Sequence[str], None] = "9861fa198790"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
